### ISSUE TITLE
{N} 3.0 support

### ISSUE THREAD

**Issue by davecoffin** [VideoSpike/nativescript-web-image-cache#34]
Is this plugin compatible with NativeScript 3.0?

**Comment by bathejasumeet** [comment]
yes, the latest version is

**Comment by bathejasumeet** [comment]
are you facing any problems with NS 3.0 compatibility?

**Comment by Cayan** [comment]
I started receiving multiple errors of "Path "" is not a valid file or resource." with the same code as before the upgrade. I think the component is loading much more before the js logic

**Comment by bachras** [comment]
I am having exactly same problem as @Cayan . I just move to NS 3.0 and updated plugins to latest versions.

**Comment by Cayan** [comment]
This is the last thing missing so I can migrate to NS 3. Even though I added multiple ngIf's to the application so the elements wouldn't be created without and src string the problem persisted.

I've added multiple debugs to the plugin and its indeed entering the setSrc function with an empty value. I made a few tests and I was unsuccessful so I gave up for the time

**Comment by bathejasumeet** [comment]
I'm sure this worked and I had resolved this.. Looking into it

**Comment by bathejasumeet** [comment]
done -- sort of shotgun surgery -- @Cayan .. thanks for the debug output... try the latest version.

Please clean the app cache from the settings. I had faced a lot of issues while fixing - many times code wasn't updated and I had to clear the cache from the app and remove platform + add platform + build (not sure if it is my device or the ns - ang4 runtime)

**Comment by Cayan** [comment]
Now it seems to be working.

you forgot this debug: instantiating common web image

I'm also receiving lots of "bad background-color value: Error: Invalid color: undefined", any idea on this?

**Comment by MuhammadTahir92** [comment]
how to clean the cache Where is the setting @Cayan  @bathejasumeet
